### ISSUE TITLE
login spam

### ISSUE THREAD

**Issue by Larsvigo** [lantisnt/MonolithDKP#22]
Is there any way to disable the chat spam every time I log in I'm an altoholic so logging in many times to check mail on them. The only thing that interest me there is if it's out of date. The rest is just irritating for me.

**Comment by lantisnt** [comment]
Hey,
First of all i suggest disabling EssentialDKP for all chars except your raiding main, as this addon loads lots of data that you don't need on alts.

I will shorten this message also, as it's legacy from MonolithDKP.
It will only show if your DKP database is up to date or not, not all the numbers.

**Comment by lantisnt** [comment]
Modified in v1.4.X
