### ISSUE TITLE
Unable to Sort Bidding Window Columns 

### ISSUE THREAD

**Issue by caspervk** [lantisnt/MonolithDKP#43]
It would be cool if you were able to sort the columns in the bidding window by pressing the column headers, just as you are able to in the dkp list in the main window.
![image](https://user-images.githubusercontent.com/2924482/83645527-e3a19280-a5b2-11ea-868c-8a01a8b4c3d4.png)

If this is not possible, it would also fit my use-case to sort first by "bid" and then secondly by "total DKP", but I'm not sure if this would be confusing for others.

Thanks for your continued work on this AddOn!

**Comment by lantisnt** [comment]
That's high on my prio list but probably it will end in (bid, maxdkp) order instead of clickable. Also the fact that you can't always scroll the bid window

**Comment by caspervk** [comment]
(bid, maxdkp) works perfectly for me. Thanks a lot!

**Comment by lantisnt** [comment]
@caspervk

**Comment by caspervk** [comment]
@lantisnt thank you!
