### ISSUE TITLE
DKP Values Stored as singles

### ISSUE THREAD

**Issue by caspervk** [lantisnt/MonolithDKP#44]
It looks like DKP values are stored as [singles](https://en.wikipedia.org/wiki/Single-precision_floating-point_format) in some places:
![image](https://user-images.githubusercontent.com/2924482/83645604-f74cf900-a5b2-11ea-9c27-e9bb33219a99.png)
On the other hand, the value is correctly shown in other places:
![image](https://user-images.githubusercontent.com/2924482/83645640-ff0c9d80-a5b2-11ea-976b-ff56b2378fdf.png)
I haven't looked through the code, but as with all currency, maybe the numbers should be stored as integers (in µDKP) or as [Decimal](https://en.wikipedia.org/wiki/Decimal_data_type)?

**Comment by lantisnt** [comment]
Values are stored properly as floats. It's display that is flawed. Could you point me to the points where you know they are displayed improperly?

**Comment by caspervk** [comment]
The problem is that storing the value as a floating point -- 32 bit single-precision floating-point especially -- results in imprecision. The the example above, `11.6`, can never be [represented](https://www.h-schmidt.net/FloatConverter/IEEE754.html) correctly in this format. Fixing the display might make the problem appear to be solved, but it will only mask the issue, and it is likely that the errors will compound. It is for this reason that any currency in a computer is either stored using fixed-point decimals or as integers in its smallest divisible unit; e.g. cents, Bitcoin Satoshi, or in this case, µDKP. The AddOn even allows us to work to four decimal places as a setting, but using the current representation it is unable to distinguish numbers to this precision, e.g. `1000.10` is actually stored and represented as `1000.0999755859375`.

**Comment by Vapok** [comment]
If it helps, this is how I fixed it:

https://github.com/Vapok/MonolithDKP/pull/6
